port 80

diff --git a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80 b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
--- a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
+++ b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
@@ -1,31 +1,30 @@
 #!/usr/bin/env bash
 # a bash code that fix the probleme when Nginx isn't listening on port 80
 
-if pgrep nginx > /dev/null; then
-	echo "Nginx is running."
-else
-	echo "Nginx is not running. Starting Nginx service..."
-	sudo service nginx start
+if ! grep -q "listen 80 default_server;" /etc/nginx/sites-enabled/default; then
+	echo "Error: 'listen 80 default_server;' is missing or misconfigured in /etc/nginx/sites-enabled/default"
+	# Find and replace the line to bind port 80 to all IPv4 addresses in the default site configuration file
+	echo "Updating the configuration to bind port 80 to all IPv4 addresses..."
+	awk '/^server {/,/^listen \[::\]:80 default_server;/ { if ($0 ~ /^ *listen [[:digit:]]+ default_server;/) print "        listen 80 default_server;"; else print; next } 1' /etc/nginx/sites-enabled/default > /tmp/default.tmp && sudo mv /tmp/default.tmp /etc/nginx/sites-enabled/default
 fi
 
-# Check if Nginx is listening on port 80
-if sudo lsof -i -P -n | grep LISTEN | grep ':80'; then
-	echo "Nginx is already listening on port 80."
-else
-	echo "Nginx is not listening on port 80. Checking Nginx configuration..."
+if sudo netstat -tuln | grep -q ":80"; then
+	echo "Error: Another web server like Apache is active and using port 80"
+	# Stop the Apache service
+	echo "Stopping Apache service..."
+	sudo systemctl stop apache2
+fi
 
-	# Add or modify Nginx configuration to listen on port 80
-	if ! grep -q 'listen 80' /etc/nginx/sites-available/default; then
-		sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
-	fi
+if ! sudo nginx -t -c /etc/nginx/nginx.conf &> /dev/null; then
+	echo "Error: Nginx is not run with sudo privileges"
+	# Restart Nginx with sudo privileges
+	echo "Restarting Nginx with sudo privileges..."
+	sudo systemctl restart nginx
+fi
 
-	# Restart Nginx service
-	sudo service nginx restart
-
-	# Verify if Nginx is now listening on port 80
-	if sudo lsof -i -P -n | grep LISTEN | grep ':80'; then
-		echo "Nginx is now listening on port 80."
-	else
-		echo "Failed to fix the issue. Please check Nginx configuration manually."
-	fi
+if sudo ufw status | grep -q "80/tcp"; then
+	echo "Error: UFW firewall configuration is restricting Nginx from binding to port 80"
+	# Allow incoming traffic on port 80
+	echo "Allowing incoming traffic on port 80..."
+	sudo ufw allow 80/tcp
 fi
